In [117]:
import pandas as pd
df = pd.read_excel(r"C:\Users\Sopuluchi\Documents\Tech\Python Repository for Data Analysis\Data cleaning in Pandas.xlsx")

In [118]:
df

,Customer Key,Name,Gender,Yearly Income,Occupation,Address,Phone Number,Not Useful Column
0,11000,"/Jon ,/Yang",Mal,90000,Professional,3761 N. 14th St,123-545-5421,True
1,11001,Eugene Huang,M,60000,Professional,2243 W St.,123/643/9775,False
2,11002,Ruben Torres,Male,60000,Professional,5844 Linden Land,7066950392,True
3,11003,...Christy Zhu,F,70000,Professional,1825 Village Pl.,123-543-2345,True
4,11004,Elizabeth Johnson,Female,80000,Manual,7553 Harness Circle,876|678|3469,True
5,11005,\\\Julio /?Ruiz,ma,70000,Clerical,7305 Humphrey Drive,304-762-2467,True
6,11006,Janet Alvarez////,F,70000,Clerical,2612 Berry Dr,NaN,False
7,11007,Marco Mehta,ma,60000,Clerical,942 Brook Street,876|678|3469,False
8,11008,Rob Verhoff,Female,60000,Manual,624 Peabody Road,N/a,False
9,11009,//Shannon Carlson,M,70000,Manual,3839 Northgate Road,123-545-5421,True
10,11010,Jacquelyn Suarez,F,70000,Manual,7800 Corrinne Court,NaN,True
11,11011,Curtis Lu,M,60000,Manual,1224 Shoenic,7066950392,True
12,11012,??Lauren Walker,fe,100000,Manual,4785 Scott Street,123-543-2345,False
13,11013,Ian Jenkins,M,100000,Manual,7902 Hudson Ave.,876|678|3469,False
14,11014,Sydney Bennett,mal,100000,Clerical,9011 Tank Drive,304-762-2467,False
15,11015,Chloe Young,F,30000,Manual,244 Willow Pass Road,123-545-5421,False
16,11016,",,/Wyatt Hill",Male,30000,Clerical,9666 Northridge Ct.,123/643/9775,False
17,11017,Shannon Wang,Female,20000,Clerical,7330 Saddlehill Lane,7066950392,True
18,11018,Clarence Rai,M,30000,Clerical,244 Rivewview,N/a,True
19,11019,"Luke Lal,,..\\",ma,40000,Skilled Manual,7832 Landing Dr,876|678|3469,True
20,11020,Jordan King,M,40000,Skilled Manual,7156 Rose Dr.,836|6201|347,True
21,11021,Destiny Wilson,Female,40000,Skilled Manual,8148 W. Lake Dr.,483/4-184019,False
22,11022,\\..?/Ethan Zhang,ma,40000,Skilled Manual,1769 Nicholas Drive,402-19/41138,False
23,11023,Seth Edwards,M,40000,Skilled Manual,4499 Valley Crest,30284..28221,True
24,11024,Russell Xie,Male,60000,Skilled Manual,8734 Oxford Place,330284..//3821,True
25,11012,??Lauren Walker,fe,100000,Manual,4785 Scott Street,123-543-2345,False
26,11002,Ruben Torres,Male,60000,Professional,5844 Linden Land,7066950392,True
27,11003,...Christy Zhu,F,70000,Professional,1825 Village Pl.,123-543-2345,True

In [119]:
df = df.drop_duplicates()                                                              # removing duplicate row

In [120]:
df = df.drop(columns = "Not Useful Column")                                            # dropping Not Useful Column column

In [121]:
df["Name"] = df["Name"].str.replace(r"[/.?,\\]", " ", regex = True)                    # removing unwanted characters everywhere

In [122]:
df[["First Name", "Last Name"]] = df["Name"].str.split(expand = True, n = 1)           # spliting "Name" column to

In [123]:
cols = df.columns.tolist()                                                             # re-arrangeing the columns position
cols.remove("First Name")
cols.remove("Last Name")

cols = [cols[0], "First Name", "Last Name"] + cols[1:]
df = df[cols]

In [124]:
df = df.drop(columns ="Name")                                                          # dropping "Name" column

In [125]:
df["Gender"] = df["Gender"].replace({"Mal": "Male", "M": "Male", "ma": "Male", "mal": "Male", "F": "Female", "fe": "Female"})
                                                                                       # replace "Male" & "Female" Gender with corresponding string

In [126]:
df["Phone Number"] = df["Phone Number"].str.replace("[^a-zA-Z0-9]", "", regex = True)  # dropping characters in the "Phone Number" column

In [127]:
df["Phone Number"] = df["Phone Number"].apply(lambda x: str(x))                        # Converting "Phone Number"column to string

In [128]:
df["Phone Number"] = df["Phone Number"].apply(lambda x: x[0:3]+ "-"+ x[3:6]+ "-"+ x[6:10])
                                                                                       # slicing through "phone Number" elements

In [129]:
df["Phone Number"] = df["Phone Number"].str.replace({"nan--": " ", "Na--": " "})       # Removing letters from "phone Number" column

In [130]:
df

,Customer Key,First Name,Last Name,Gender,Yearly Income,Occupation,Address,Phone Number
0,11000,Jon,Yang,Male,90000,Professional,3761 N. 14th St,123-545-5421
1,11001,Eugene,Huang,Male,60000,Professional,2243 W St.,123-643-9775
2,11002,Ruben,Torres,Male,60000,Professional,5844 Linden Land,
3,11003,Christy,Zhu,Female,70000,Professional,1825 Village Pl.,123-543-2345
4,11004,Elizabeth,Johnson,Female,80000,Manual,7553 Harness Circle,876-678-3469
5,11005,Julio,Ruiz,Male,70000,Clerical,7305 Humphrey Drive,304-762-2467
6,11006,Janet,Alvarez,Female,70000,Clerical,2612 Berry Dr,
7,11007,Marco,Mehta,Male,60000,Clerical,942 Brook Street,876-678-3469
8,11008,Rob,Verhoff,Female,60000,Manual,624 Peabody Road,
9,11009,Shannon,Carlson,Male,70000,Manual,3839 Northgate Road,123-545-5421
10,11010,Jacquelyn,Suarez,Female,70000,Manual,7800 Corrinne Court,
11,11011,Curtis,Lu,Male,60000,Manual,1224 Shoenic,
12,11012,Lauren,Walker,Female,100000,Manual,4785 Scott Street,123-543-2345
13,11013,Ian,Jenkins,Male,100000,Manual,7902 Hudson Ave.,876-678-3469
14,11014,Sydney,Bennett,Male,100000,Clerical,9011 Tank Drive,304-762-2467
15,11015,Chloe,Young,Female,30000,Manual,244 Willow Pass Road,123-545-5421
16,11016,Wyatt,Hill,Male,30000,Clerical,9666 Northridge Ct.,123-643-9775
17,11017,Shannon,Wang,Female,20000,Clerical,7330 Saddlehill Lane,
18,11018,Clarence,Rai,Male,30000,Clerical,244 Rivewview,
19,11019,Luke,Lal,Male,40000,Skilled Manual,7832 Landing Dr,876-678-3469
20,11020,Jordan,King,Male,40000,Skilled Manual,7156 Rose Dr.,836-620-1347
21,11021,Destiny,Wilson,Female,40000,Skilled Manual,8148 W. Lake Dr.,483-418-4019
22,11022,Ethan,Zhang,Male,40000,Skilled Manual,1769 Nicholas Drive,402-194-1138
23,11023,Seth,Edwards,Male,40000,Skilled Manual,4499 Valley Crest,302-842-8221
24,11024,Russell,Xie,Male,60000,Skilled Manual,8734 Oxford Place,330-284-3821

In [87]:
# Questions: How do you handle missing values?
# Answer: I either replace, impute or remove them, depending on the Business context.

# In the case of our dataframe, we will ensure we get the phone numbers of all the customers with missing values in the Phone_number
# column and impute them, because we can not delete an entire records, just because of missing phone-number.

In [91]:
# My name is Ugwuoke Solomon Sopuluci, i am a Data Analyst with 3 years of experience using data to solve Business problems

# please visit my portfolio to download the complete IPYNB project @: https://github.com/sopuluchisolomon